#Dirección de la base de datos y número de puerto
spring.datasource.url=jdbc:postgresql://ec2-52-4-104-184.compute-1.amazonaws.com:5432/d2hgu4ungaah2p
#Cuenta (el valor predeterminado es postgres)
spring.datasource.username=ngclnlhmjrbsqw
#contraseña
spring.datasource.password=61815779c0ee3e1495ea41329f7f9e28dc87be62d75fbec7da8c50b68dffcf80
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always